
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;


public class login_signup extends javax.swing.JFrame implements ActionListener{

    public login_signup() {
        initComponents();
//        Dimension d = new Dimension(Toolkit.getDefaultToolkit().getScreenSize());
        
        setSize(500,400);
        setVisible(true);
       
        bt1.addActionListener(this);
        bt2.addActionListener(this);
        
//        int width = (int) d.getWidth();
//        int height = (int)d.getHeight();
//        
//         back.setBounds(0, 0,width ,height );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lb1 = new javax.swing.JLabel();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
       

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lb1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lb1.setText("INTERACTION");
        getContentPane().add(lb1);
        lb1.setBounds(140, 20, 200, 30);

       
        
        bt1.setText("LOGIN");
        bt1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        bt1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(bt1);
        bt1.setBounds(70, 180, 160, 50);

        // NOI18N
        bt2.setText("SIGNUP");
        bt2.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        bt2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(bt2);
        bt2.setBounds(280, 180, 160, 50);


        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JLabel lb1;
    // End of variables declaration                   

    @Override
    public void actionPerformed(ActionEvent e) 
    {
       if(e.getSource()==bt1)
       {
           login obj=new login();
       }
       else if(e.getSource()==bt2)
       {
           signup obj1=new signup();
       }
    }
}
