
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class server_on_off extends javax.swing.JFrame {

    server obj;
    public server_on_off() {
        
        initComponents();
        stopbt.setEnabled(false);
        setVisible(true);
        setSize(400,400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stopbt = new javax.swing.JButton();
        startbt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        login_signupbt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        stopbt.setFont(new java.awt.Font("Segoe UI Semibold", 2, 24)); // NOI18N
        stopbt.setText("STOP");
        stopbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopbtActionPerformed(evt);
            }
        });
        getContentPane().add(stopbt);
        stopbt.setBounds(110, 190, 140, 40);

        startbt.setFont(new java.awt.Font("Segoe UI Semibold", 2, 24)); // NOI18N
        startbt.setText("START");
        startbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startbtActionPerformed(evt);
            }
        });
        getContentPane().add(startbt);
        startbt.setBounds(110, 110, 140, 40);

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 32)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SERVER ON OFF");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 390, 60);

        login_signupbt.setFont(new java.awt.Font("Segoe UI Semibold", 3, 24)); // NOI18N
        login_signupbt.setText("LOGIN/SIGNUP");
        login_signupbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_signupbtActionPerformed(evt);
            }
        });
        getContentPane().add(login_signupbt);
        login_signupbt.setBounds(80, 270, 210, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stopbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopbtActionPerformed
         obj.shutdown();
        startbt.setEnabled(true);
        stopbt.setEnabled(false);
       
        
    }//GEN-LAST:event_stopbtActionPerformed

    private void startbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startbtActionPerformed
        try 
            
        {
            obj=new server(9000);
            JOptionPane.showMessageDialog(rootPane, "SERVER STARTED");
            startbt.setEnabled(false);
            stopbt.setEnabled(true);
        } 
        catch (IOException ex) 
        {
            ex.printStackTrace();
        }   
    }//GEN-LAST:event_startbtActionPerformed

    private void login_signupbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_signupbtActionPerformed
        login_signup ls=new login_signup();
    }//GEN-LAST:event_login_signupbtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(server_on_off.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(server_on_off.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(server_on_off.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(server_on_off.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new server_on_off().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton login_signupbt;
    private javax.swing.JButton startbt;
    private javax.swing.JButton stopbt;
    // End of variables declaration//GEN-END:variables
}
