
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


public class signup extends javax.swing.JFrame {

    File ph;
    JFileChooser jfc;
    public signup() {
        initComponents();
        setSize(500,600);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernamelb = new javax.swing.JLabel();
        Usernametf = new javax.swing.JTextField();
        emaillb = new javax.swing.JLabel();
        Emailtf = new javax.swing.JTextField();
        passwordlb = new javax.swing.JLabel();
        phonelb = new javax.swing.JLabel();
        phonetf = new javax.swing.JTextField();
        passwordtf = new javax.swing.JPasswordField();
        photolb = new javax.swing.JLabel();
        photolb1 = new javax.swing.JLabel();
        browsebt = new javax.swing.JButton();
        submitbt = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        usernamelb.setText("Username");
        getContentPane().add(usernamelb);
        usernamelb.setBounds(20, 80, 90, 30);
        getContentPane().add(Usernametf);
        Usernametf.setBounds(120, 80, 350, 30);

        emaillb.setText("Email");
        getContentPane().add(emaillb);
        emaillb.setBounds(20, 140, 90, 30);
        getContentPane().add(Emailtf);
        Emailtf.setBounds(120, 140, 350, 30);

        passwordlb.setText("Password");
        getContentPane().add(passwordlb);
        passwordlb.setBounds(20, 200, 90, 30);

        phonelb.setText("Phone");
        getContentPane().add(phonelb);
        phonelb.setBounds(20, 270, 90, 30);
        getContentPane().add(phonetf);
        phonetf.setBounds(120, 270, 350, 30);
        getContentPane().add(passwordtf);
        passwordtf.setBounds(120, 200, 350, 30);

        photolb.setText("Photo");
        getContentPane().add(photolb);
        photolb.setBounds(20, 380, 80, 30);

        photolb1.setText("preview");
        getContentPane().add(photolb1);
        photolb1.setBounds(130, 350, 160, 120);

        browsebt.setText("Browse");
        browsebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsebtActionPerformed(evt);
            }
        });
        getContentPane().add(browsebt);
        browsebt.setBounds(370, 350, 110, 30);

        submitbt.setText("Submit");
        submitbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtActionPerformed(evt);
            }
        });
        getContentPane().add(submitbt);
        submitbt.setBounds(370, 400, 110, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 32)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sign Up");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 10, 490, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browsebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsebtActionPerformed
       jfc=new JFileChooser();
       int ans=jfc.showOpenDialog(this);
       if(ans==JFileChooser.APPROVE_OPTION)
       {
           ph=jfc.getSelectedFile();
           ImageIcon ic = new ImageIcon(ph.getPath());
          
          Image img = ic.getImage().getScaledInstance(photolb1.getWidth(), photolb1.               getHeight(), Image.SCALE_SMOOTH);
          
          ImageIcon ic1 = new ImageIcon(img);
          photolb1.setIcon(ic1);
       }
    }//GEN-LAST:event_browsebtActionPerformed

    private void submitbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtActionPerformed
        
        String username=Usernametf.getText();
        String email=Emailtf.getText();
        String password=passwordtf.getText();
        String phone=phonetf.getText();
        if(username.isEmpty()||email.isEmpty()||password.equals("")||phone.isEmpty()||ph == null)
        {
         JOptionPane.showMessageDialog(rootPane, "All fileds are Mandatory");
        }
        else
        {
            String result=client.SignUp(username, email, password, phone, ph);
            if(result.trim().equals("exists"))
            {
                JOptionPane.showMessageDialog(rootPane, "Already Exist");
            }
            else if(result.trim().equals("success"))
            {
                JOptionPane.showMessageDialog(rootPane, "Success");
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, result);
            }
            Usernametf.setText("");
            Emailtf.setText("");
            passwordtf.setText("");
            phonetf.setText("");
            photolb1.setIcon(null);
            photolb1.setText("preview");
            Usernametf.requestFocus();
        }
    }//GEN-LAST:event_submitbtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Dark".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Emailtf;
    private javax.swing.JTextField Usernametf;
    private javax.swing.JButton browsebt;
    private javax.swing.JLabel emaillb;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel passwordlb;
    private javax.swing.JPasswordField passwordtf;
    private javax.swing.JLabel phonelb;
    private javax.swing.JTextField phonetf;
    private javax.swing.JLabel photolb;
    private javax.swing.JLabel photolb1;
    private javax.swing.JButton submitbt;
    private javax.swing.JLabel usernamelb;
    // End of variables declaration//GEN-END:variables
}
